# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - binary: spiffe-helper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/spiffe-helper

archives:
  - formats: [ 'tar.gz' ]
    builds:
      - spiffe-helper
    id: spiffe-helper
    # This name template makes the OS and Arch compatible with the results of `uname`
    name_template: >-
      spiffe-helper_{{- .Version}}_
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
    # Use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

dockers:
  - id: spiffe-helper-amd64
    goarch: amd64
    image_templates:
      - "ghcr.io/faisal-memon/spiffe-helper:{{ .Version}}-amd64"
    use: buildx
    dockerfile: Dockerfile-goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: spiffe-helper-arm64
    goarch: arm64
    image_templates:
      - "ghcr.io/faisal-memon/spiffe-helper:{{ .Version}}-arm64"
    use: buildx
    dockerfile: Dockerfile-goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/faisal-memon/spiffe-helper:{{ .Version}}"
    image_templates:
      - "ghcr.io/faisal-memon/spiffe-helper:{{ .Version}}-amd64"
      - "ghcr.io/faisal-memon/spiffe-helper:{{ .Version}}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
