name: Update Go Version

on:
  schedule:
    # Random minute number to avoid GH scheduler stampede
    - cron: '23 16 * * 1'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  update-go-version:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Update Go version
        id: update
        uses: faisal-memon/update-go-mod-action@v1

      - name: Setup Go
        if: steps.update.outputs.changed == 'true'
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Tidy Go modules
        if: steps.update.outputs.changed == 'true'
        run: go mod tidy

      - name: Create pull request
        if: steps.update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          branch: automation/update-go-version
          commit-message: Update Go version to ${{ steps.update.outputs.latest-version }}
          title: Update Go version to ${{ steps.update.outputs.latest-version }}
          body: |
            Updates the `go.mod` Go version to the latest stable release.
          signoff: true
          delete-branch: true
